#!/bin/bash

sudo X &
export DISPLAY=:0.0

sudo nvidia-settings -a '[gpu:0]/GPUFanControlState=0'
sudo nvidia-settings -a '[gpu:1]/GPUFanControlState=0'
sudo nvidia-settings -a '[gpu:2]/GPUFanControlState=0'

sudo nvidia-settings -a '[gpu:0]/GPUMemoryTransferRateOffsetAllPerformanceLevels[3]=0'
sudo nvidia-settings -a '[gpu:1]/GPUMemoryTransferRateOffsetAllPerformanceLevels[3]=0'
sudo nvidia-settings -a '[gpu:2]/GPUMemoryTransferRateOffsetAllPerformanceLevels[3]=0'

sudo nvidia-settings -a '[gpu:0]/GPUGraphicsClockOffsetAllPerformanceLevels[3]=0'
sudo nvidia-settings -a '[gpu:1]/GPUGraphicsClockOffsetAllPerformanceLevels[3]=0'
sudo nvidia-settings -a '[gpu:2]/GPUGraphicsClockOffsetAllPerformanceLevels[3]=0'
