#!/bin/bash

sudo X &
export DISPLAY=:0.0

sudo nvidia-smi -pm 1

sudo nvidia-smi -i 0 -pl 124
sudo nvidia-smi -i 1 -pl 120
sudo nvidia-smi -i 2 -pl 113

sudo nvidia-settings -a '[gpu:0]/GPUFanControlState=1' -a '[fan:0]/GPUTargetFanSpeed=65'
sudo nvidia-settings -a '[gpu:1]/GPUFanControlState=1' -a '[fan:1]/GPUTargetFanSpeed=65'
sudo nvidia-settings -a '[gpu:2]/GPUFanControlState=1' -a '[fan:2]/GPUTargetFanSpeed=65'
sudo nvidia-settings -a '[fan:3]/GPUTargetFanSpeed=65'
sudo nvidia-settings -a '[fan:4]/GPUTargetFanSpeed=65'
sudo nvidia-settings -a '[fan:5]/GPUTargetFanSpeed=65'

sudo nvidia-settings -a '[gpu:0]/GPUMemoryTransferRateOffsetAllPerformanceLevels[3]=2600'
sudo nvidia-settings -a '[gpu:1]/GPUMemoryTransferRateOffsetAllPerformanceLevels[3]=2600'
sudo nvidia-settings -a '[gpu:2]/GPUMemoryTransferRateOffsetAllPerformanceLevels[3]=2600'

sudo nvidia-settings -a '[gpu:0]/GPUGraphicsClockOffsetAllPerformanceLevels[3]=-200'
sudo nvidia-settings -a '[gpu:1]/GPUGraphicsClockOffsetAllPerformanceLevels[3]=-200'
sudo nvidia-settings -a '[gpu:2]/GPUGraphicsClockOffsetAllPerformanceLevels[3]=-200'
